// === Video Types ===

export type VideoType = "youtube" | "social" | "text-animation" | "marketing";
export type VideoStatus =
  | "pending"
  | "generating"
  | "rendering"
  | "completed"
  | "failed";
export type VideoResolution = "1920x1080" | "1080x1920" | "1080x1080" | "1280x720";

// === Scene Types ===

export type SceneType =
  | "intro"
  | "text-animation"
  | "bullet-list"
  | "stat"
  | "quote"
  | "timeline"
  | "split"
  | "image"
  | "split-screen"   // legacy alias → renders as split
  | "outro"
  | "transition";

export type AnimationType =
  | "fadeIn"
  | "fadeOut"
  | "slideInLeft"
  | "slideInRight"
  | "slideInUp"
  | "slideInDown"
  | "zoomIn"
  | "zoomOut"
  | "typewriter"
  | "none";

export interface TextElement {
  content: string;
  fontSize?: number;
  fontWeight?: "normal" | "bold" | "black";
  color?: string;
  align?: "left" | "center" | "right";
  animation?: AnimationType;
  animationDelay?: number;
}

// === Rich data structures for new scene types ===

export interface BulletItem {
  icon?: string;    // emoji e.g. "✅", "🚀", "💡"
  text: string;
}

export interface StatItem {
  value: string;   // "95%", "1.2M", "10x"
  label: string;
  color?: string;
}

export interface TimelineStep {
  number: number;
  title: string;
  description?: string;
}

export interface SplitPanel {
  title?: string;
  body?: string;
  items?: string[];  // bullet items without icons
  icon?: string;     // large emoji displayed prominently
}

// === Scene ===

export interface Scene {
  id: string;
  type: SceneType;
  duration: number;        // seconds
  background?: string;     // "#hex" or "gradient:#from,#to"
  overlay?: string;        // "rgba(...)" semi-transparent overlay

  // Text elements — used by intro, outro, text-animation, quote, stat header
  title?: TextElement;
  subtitle?: TextElement;
  body?: TextElement;

  // bullet-list scene
  bullets?: BulletItem[];

  // stat scene
  stats?: StatItem[];

  // timeline scene
  steps?: TimelineStep[];

  // split scene
  splitLeft?: SplitPanel;
  splitRight?: SplitPanel;

  // image scene (future)
  imageUrl?: string;
}

// === Video Spec - generated by AI ===

export interface VideoSpec {
  type: VideoType;
  title: string;
  duration: number;  // total seconds
  fps: 24 | 30 | 60;
  resolution: VideoResolution;
  colorPalette: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
  };
  font: {
    heading: string;
    body: string;
  };
  scenes: Scene[];
  audio?: {
    backgroundMusic?: string;
    voiceover?: string;
  };
}

// === Video Record (stored in DB) ===

export interface VideoRecord {
  id: string;
  projectId: string;
  title: string;
  prompt: string;
  spec: string | null;  // JSON-serialized VideoSpec
  generationMode: "template" | "ai-code";
  generatedCode: string | null;
  status: VideoStatus;
  outputPath: string | null;
  thumbnailPath: string | null;
  errorMessage: string | null;
  durationSeconds: number | null;
  createdAt: string;
  updatedAt: string;
}
