// === Video Types ===

export type VideoType = "youtube" | "social" | "text-animation" | "marketing";
export type VideoStatus =
  | "pending"
  | "generating"
  | "rendering"
  | "completed"
  | "failed";
export type VideoResolution = "1920x1080" | "1080x1920" | "1080x1080" | "1280x720";

// === Scene Types ===

export type SceneType =
  | "intro"
  | "text-animation"
  | "image"
  | "split-screen"
  | "outro"
  | "transition";

export type AnimationType =
  | "fadeIn"
  | "fadeOut"
  | "slideInLeft"
  | "slideInRight"
  | "slideInUp"
  | "slideInDown"
  | "zoomIn"
  | "zoomOut"
  | "typewriter"
  | "none";

export interface TextElement {
  content: string;
  fontSize?: number;
  fontWeight?: "normal" | "bold" | "black";
  color?: string;
  align?: "left" | "center" | "right";
  animation?: AnimationType;
  animationDelay?: number;
}

export interface Scene {
  id: string;
  type: SceneType;
  duration: number; // seconds
  background?: string; // color hex or "gradient:from,to"
  title?: TextElement;
  subtitle?: TextElement;
  body?: TextElement;
  imageUrl?: string;
  overlay?: string; // color with opacity "rgba(...)"
}

// === Video Spec - generated by Gemini ===

export interface VideoSpec {
  type: VideoType;
  title: string;
  duration: number; // total seconds
  fps: 24 | 30 | 60;
  resolution: VideoResolution;
  colorPalette: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
  };
  font: {
    heading: string;
    body: string;
  };
  scenes: Scene[];
  audio?: {
    backgroundMusic?: string; // "upbeat" | "calm" | "dramatic" | "none"
    voiceover?: string; // script text for TTS (future)
  };
}

// === Video Record (stored in DB) ===

export interface VideoRecord {
  id: string;
  projectId: string;
  title: string;
  prompt: string;
  spec: string | null; // JSON-serialized VideoSpec
  status: VideoStatus;
  outputPath: string | null;
  thumbnailPath: string | null;
  errorMessage: string | null;
  durationSeconds: number | null;
  createdAt: string;
  updatedAt: string;
}
